data_path = ""
#data_path = "/opt/gog/Vangers/game" #Linux (example)
#data_path = "/Applications/GOG/Vangers.app/Contents/Resources/game" #OSX

[game]
level = "Fostral" # see `wrlds.dat` for the list
cycle = "Eleerection" # see `bunches.prm` for the list, leave empty for bonus worlds
view = "Perspective" # can be "Flat" or "Perspective"

[game.other]
count = 10 # number of NPC vangers

[game.physics]
max_quant = 0.05

[car]
id = "OxidizeMonk"
slots = []
#id = "IronShadow"
#slots = ["HeavyLaser", "LightMissile", "LightFireBall"]

[window]
title = "Rusty Road"
size = [1280, 800]

[render.light]
pos = [1, 2, 4, 0] # w=0 for directional, w=1 for point light
color = [1, 1, 1, 1]

[render.debug]
max_vertices = 512
collision_shapes = false
impulses = false
