data_path = "/opt/gog/Vangers/game" #Linux (example)
#data_path = "/Applications/GOG/Vangers.app/Contents/Resources/game" #OSX

[game]
level = "Fostral"
cycle = "Plump-up"
other_vangers = 10

[car]
id = "OxidizeMonk"
slots = []
#id = "IronShadow"
#slots = ["HeavyLaser", "LightMissile", "LightFireBall"]

[window]
title = "Rusty Road"
size = [1280, 800]

[render.debug]
max_vertices = 512
collision_shapes = false
impulses = false
